(in-package :sdl3)

;;; gamepad properties
(defconstant +prop-gamepad-cap-mono-led-boolean+ sdl3-ffi:+sdl-prop-joystick-cap-mono-led-boolean+)
(defconstant +prop-gamepad-cap-rgb-led-boolean+ sdl3-ffi:+sdl-prop-joystick-cap-rgb-led-boolean+)
(defconstant +prop-gamepad-cap-player-led-boolean+ sdl3-ffi:+sdl-prop-joystick-cap-player-led-boolean+)
(defconstant +prop-gamepad-cap-rumble-boolean+ sdl3-ffi:+sdl-prop-joystick-cap-rumble-boolean+)
(defconstant +prop-gamepad-cap-trigger-rumble-boolean+ sdl3-ffi:+sdl-prop-joystick-cap-trigger-rumble-boolean+)

(defconstant +gamepad-axis-invalid+ sdl3-ffi:+sdl-gamepad-axis-invalid+)
(defconstant +gamepad-axis-leftx+ sdl3-ffi:+sdl-gamepad-axis-leftx+)
(defconstant +gamepad-axis-lefty+ sdl3-ffi:+sdl-gamepad-axis-lefty+)
(defconstant +gamepad-axis-rightx+ sdl3-ffi:+sdl-gamepad-axis-rightx+)
(defconstant +gamepad-axis-righty+ sdl3-ffi:+sdl-gamepad-axis-righty+)
(defconstant +gamepad-axis-left-trigger+ sdl3-ffi:+sdl-gamepad-axis-left-trigger+)
(defconstant +gamepad-axis-right-trigger+ sdl3-ffi:+sdl-gamepad-axis-right-trigger+)
(defconstant +gamepad-axis-count+ sdl3-ffi:+sdl-gamepad-axis-count+)

(defconstant +gamepad-button-invalid+ sdl3-ffi:+sdl-gamepad-button-invalid+)
(defconstant +gamepad-button-south+ sdl3-ffi:+sdl-gamepad-button-south+
  "Bottom face button (e.g. Xbox A button)")
(defconstant +gamepad-button-east+ sdl3-ffi:+sdl-gamepad-button-east+
  "Right face button (e.g. Xbox B button)")
(defconstant +gamepad-button-north+ sdl3-ffi:+sdl-gamepad-button-north+
  "Top face button (e.g. Xbox Y button)")
(defconstant +gamepad-button-back+ sdl3-ffi:+sdl-gamepad-button-back+)
(defconstant +gamepad-button-guide+ sdl3-ffi:+sdl-gamepad-button-guide+)
(defconstant +gamepad-button-start+ sdl3-ffi:+sdl-gamepad-button-start+)
(defconstant +gamepad-button-left-stick+ sdl3-ffi:+sdl-gamepad-button-left-stick+)
(defconstant +gamepad-button-right-stick+ sdl3-ffi:+sdl-gamepad-button-right-stick+)
(defconstant +gamepad-button-left-shoulder+ sdl3-ffi:+sdl-gamepad-button-left-shoulder+)
(defconstant +gamepad-button-right-shoulder+ sdl3-ffi:+sdl-gamepad-button-right-shoulder+)
(defconstant +gamepad-button-dpad-up+ sdl3-ffi:+sdl-gamepad-button-dpad-up+)
(defconstant +gamepad-button-dpad-down+ sdl3-ffi:+sdl-gamepad-button-dpad-down+)
(defconstant +gamepad-button-dpad-left+ sdl3-ffi:+sdl-gamepad-button-dpad-left+)
(defconstant +gamepad-button-dpad-right+ sdl3-ffi:+sdl-gamepad-button-dpad-right+)
(defconstant +gamepad-button-misc1+ sdl3-ffi:+sdl-gamepad-button-misc1+
  "Additional button (e.g. Xbox Series X share button, PS5 microphone button,
Nintendo Switch Pro capture button, Amazon Luna microphone button, Google Stadia
 capture button)")
(defconstant +gamepad-button-right-paddle1+ sdl3-ffi:+sdl-gamepad-button-right-paddle1+
  "Upper or primary paddle, under your right hand (e.g. Xbox Elite paddle P1)")
(defconstant +gamepad-button-left-paddle1+ sdl3-ffi:+sdl-gamepad-button-left-paddle1+
  "Upper or primary paddle, under your left hand (e.g. Xbox Elite paddle P3)")
(defconstant +gamepad-button-right-paddle2+ sdl3-ffi:+sdl-gamepad-button-right-paddle2+
  "Lower or secondary paddle, under your right hand (e.g. Xbox Elite paddle P2)")
(defconstant +gamepad-button-left-paddle2+ sdl3-ffi:+sdl-gamepad-button-left-paddle2+
  "Lower or secondary paddle, under your left hand (e.g. Xbox Elite paddle P2)")
(defconstant +gamepad-button-touchpad+ sdl3-ffi:+sdl-gamepad-button-touchpad+
  "PS4/PS5 touchpad button")
(defconstant +gamepad-button-misc2+ sdl3-ffi:+sdl-gamepad-button-misc2+)
(defconstant +gamepad-button-misc3+ sdl3-ffi:+sdl-gamepad-button-misc3+)
(defconstant +gamepad-button-misc4+ sdl3-ffi:+sdl-gamepad-button-misc4+)
(defconstant +gamepad-button-misc5+ sdl3-ffi:+sdl-gamepad-button-misc5+)
(defconstant +gamepad-button-misc6+ sdl3-ffi:+sdl-gamepad-button-misc6+)
(defconstant +gamepad-button-count+ sdl3-ffi:+sdl-gamepad-button-count+)

(defconstant +gamepad-button-label-unknown+ sdl3-ffi:+sdl-gamepad-button-label-unknown+)
(defconstant +gamepad-button-label-a+ sdl3-ffi:+sdl-gamepad-button-label-a+)
(defconstant +gamepad-button-label-b+ sdl3-ffi:+sdl-gamepad-button-label-b+)
(defconstant +gamepad-button-label-x+ sdl3-ffi:+sdl-gamepad-button-label-x+)
(defconstant +gamepad-button-label-y+ sdl3-ffi:+sdl-gamepad-button-label-y+)
(defconstant +gamepad-button-label-cross+ sdl3-ffi:+sdl-gamepad-button-label-cross+)
(defconstant +gamepad-button-label-circle+ sdl3-ffi:+sdl-gamepad-button-label-circle+)
(defconstant +gamepad-button-label-square+ sdl3-ffi:+sdl-gamepad-button-label-square+)
(defconstant +gamepad-button-label-triangle+ sdl3-ffi:+sdl-gamepad-button-label-triangle+)

;;; joystick properties
(defconstant +prop-joystick-cap-mono-led-boolean+ sdl3-ffi:+sdl-prop-joystick-cap-mono-led-boolean+)
(defconstant +prop-joystick-cap-rgb-led-boolean+ sdl3-ffi:+sdl-prop-joystick-cap-rgb-led-boolean+)
(defconstant +prop-joystick-cap-player-led-boolean+ sdl3-ffi:+sdl-prop-joystick-cap-player-led-boolean+)
(defconstant +prop-joystick-cap-rumble-boolean+ sdl3-ffi:+sdl-prop-joystick-cap-rumble-boolean+)
(defconstant +prop-joystick-cap-trigger-rumble-boolean+ sdl3-ffi:+sdl-prop-joystick-cap-trigger-rumble-boolean+)

;;; pixel formats
(defconstant +pixelformat-unknown+ sdl3-ffi:+sdl-pixelformat-unknown+)
(defconstant +pixelformat-index1lsb+ sdl3-ffi:+sdl-pixelformat-index1lsb+)
(defconstant +pixelformat-index1msb+ sdl3-ffi:+sdl-pixelformat-index1msb+)
(defconstant +pixelformat-index2lsb+ sdl3-ffi:+sdl-pixelformat-index2lsb+)
(defconstant +pixelformat-index12msb+ sdl3-ffi:+sdl-pixelformat-index2msb+)
(defconstant +pixelformat-index4lsb+ sdl3-ffi:+sdl-pixelformat-index4lsb+)
(defconstant +pixelformat-index14msb+ sdl3-ffi:+sdl-pixelformat-index4msb+)
(defconstant +pixelformat-index8+ sdl3-ffi:+sdl-pixelformat-index8+)
(defconstant +pixelformat-rgb332+ sdl3-ffi:+sdl-pixelformat-rgb332+)
(defconstant +pixelformat-xrgb4444+ sdl3-ffi:+sdl-pixelformat-xrgb4444+)
(defconstant +pixelformat-xbgr4444+ sdl3-ffi:+sdl-pixelformat-xbgr4444+)
(defconstant +pixelformat-xrgb1555+ sdl3-ffi:+sdl-pixelformat-xrgb1555+)
(defconstant +pixelformat-xbgr1555+ sdl3-ffi:+sdl-pixelformat-xbgr1555+)
(defconstant +pixelformat-argb4444+ sdl3-ffi:+sdl-pixelformat-argb4444+)
(defconstant +pixelformat-rgba4444+ sdl3-ffi:+sdl-pixelformat-rgba4444+)
(defconstant +pixelformat-abgr4444+ sdl3-ffi:+sdl-pixelformat-abgr4444+)
(defconstant +pixelformat-bgra4444+ sdl3-ffi:+sdl-pixelformat-bgra4444+)
(defconstant +pixelformat-argb1555+ sdl3-ffi:+sdl-pixelformat-argb1555+)
(defconstant +pixelformat-argba5551+ sdl3-ffi:+sdl-pixelformat-rgba5551+)
(defconstant +pixelformat-abgr1555+ sdl3-ffi:+sdl-pixelformat-abgr1555+)
(defconstant +pixelformat-bgra5551+ sdl3-ffi:+sdl-pixelformat-bgra5551+)
(defconstant +pixelformat-rgb565+ sdl3-ffi:+sdl-pixelformat-rgb565+)
(defconstant +pixelformat-bgr565+ sdl3-ffi:+sdl-pixelformat-bgr565+)
(defconstant +pixelformat-rgb24+ sdl3-ffi:+sdl-pixelformat-rgb24+)
(defconstant +pixelformat-bgr24+ sdl3-ffi:+sdl-pixelformat-bgr24+)
(defconstant +pixelformat-xrgb8888+ sdl3-ffi:+sdl-pixelformat-xrgb8888+)
(defconstant +pixelformat-rgbx8888+ sdl3-ffi:+sdl-pixelformat-rgbx8888+)
(defconstant +pixelformat-xbgr8888+ sdl3-ffi:+sdl-pixelformat-xbgr8888+)
(defconstant +pixelformat-bgrx8888+ sdl3-ffi:+sdl-pixelformat-bgrx8888+)
(defconstant +pixelformat-argb8888+ sdl3-ffi:+sdl-pixelformat-argb8888+)
(defconstant +pixelformat-rgba8888+ sdl3-ffi:+sdl-pixelformat-rgba8888+)
(defconstant +pixelformat-abgr8888+ sdl3-ffi:+sdl-pixelformat-abgr8888+)
(defconstant +pixelformat-bgra8888+ sdl3-ffi:+sdl-pixelformat-bgra8888+)
(defconstant +pixelformat-xrgb2101010+ sdl3-ffi:+sdl-pixelformat-xrgb2101010+)
(defconstant +pixelformat-xbgr2101010+ sdl3-ffi:+sdl-pixelformat-xbgr2101010+)
(defconstant +pixelformat-argb2101010+ sdl3-ffi:+sdl-pixelformat-argb2101010+)
(defconstant +pixelformat-abgr2101010+ sdl3-ffi:+sdl-pixelformat-abgr2101010+)
(defconstant +pixelformat-rgb48+ sdl3-ffi:+sdl-pixelformat-rgb48+)
(defconstant +pixelformat-bgr48+ sdl3-ffi:+sdl-pixelformat-bgr48+)
(defconstant +pixelformat-rgba64+ sdl3-ffi:+sdl-pixelformat-rgba64+)
(defconstant +pixelformat-argb64+ sdl3-ffi:+sdl-pixelformat-argb64+)
(defconstant +pixelformat-bgra64+ sdl3-ffi:+sdl-pixelformat-bgra64+)
(defconstant +pixelformat-abgr64+ sdl3-ffi:+sdl-pixelformat-abgr64+)
(defconstant +pixelformat-rgb48-float+ sdl3-ffi:+sdl-pixelformat-rgb48-float+)
(defconstant +pixelformat-bgr48-float+ sdl3-ffi:+sdl-pixelformat-bgr48-float+)
(defconstant +pixelformat-rgba64-float+ sdl3-ffi:+sdl-pixelformat-rgba64-float+)
(defconstant +pixelformat-argb64-float+ sdl3-ffi:+sdl-pixelformat-argb64-float+)
(defconstant +pixelformat-bgra64-float+ sdl3-ffi:+sdl-pixelformat-bgra64-float+)
(defconstant +pixelformat-abgr64-float+ sdl3-ffi:+sdl-pixelformat-abgr64-float+)
(defconstant +pixelformat-rgb96-float+ sdl3-ffi:+sdl-pixelformat-rgb96-float+)
(defconstant +pixelformat-bgr96-float+ sdl3-ffi:+sdl-pixelformat-bgr96-float+)
(defconstant +pixelformat-rgba128-float+ sdl3-ffi:+sdl-pixelformat-rgba128-float+)
(defconstant +pixelformat-argb128-float+ sdl3-ffi:+sdl-pixelformat-argb128-float+)
(defconstant +pixelformat-bgra128-float+ sdl3-ffi:+sdl-pixelformat-bgra128-float+)
(defconstant +pixelformat-abgr128-float+ sdl3-ffi:+sdl-pixelformat-abgr128-float+)
(defconstant +pixelformat-yv12+ sdl3-ffi:+sdl-pixelformat-yv12+)
(defconstant +pixelformat-iyuv+ sdl3-ffi:+sdl-pixelformat-iyuv+)
(defconstant +pixelformat-yuy2+ sdl3-ffi:+sdl-pixelformat-yuy2+)
(defconstant +pixelformat-uyvy+ sdl3-ffi:+sdl-pixelformat-uyvy+)
(defconstant +pixelformat-yvyu+ sdl3-ffi:+sdl-pixelformat-yvyu+)
(defconstant +pixelformat-nv12+ sdl3-ffi:+sdl-pixelformat-nv12+)
(defconstant +pixelformat-anv21+ sdl3-ffi:+sdl-pixelformat-nv21+)
(defconstant +pixelformat-p010+ sdl3-ffi:+sdl-pixelformat-p010+)
(defconstant +pixelformat-external-oes+ sdl3-ffi:+sdl-pixelformat-external-oes+)
(defconstant +pixelformat-mjpg+ sdl3-ffi:+sdl-pixelformat-mjpg+)
(defconstant +pixelformat-rgba32+ sdl3-ffi:+sdl-pixelformat-rgba32+)
(defconstant +pixelformat-argb32+ sdl3-ffi:+sdl-pixelformat-argb32+)
(defconstant +pixelformat-bgra32+ sdl3-ffi:+sdl-pixelformat-bgra32+)
(defconstant +pixelformat-abgr32+ sdl3-ffi:+sdl-pixelformat-abgr32+)
(defconstant +pixelformat-xrgb32+ sdl3-ffi:+sdl-pixelformat-xrgb32+)
(defconstant +pixelformat-bgrx32+ sdl3-ffi:+sdl-pixelformat-bgrx32+)
(defconstant +pixelformat-xbgr32+ sdl3-ffi:+sdl-pixelformat-xbgr32+)

;;; pixel types
(defconstant +pixeltype-unknown+ sdl3-ffi:+sdl-pixeltype-unknown+)
(defconstant +pixeltype-index1+ sdl3-ffi:+sdl-pixeltype-index1+)
(defconstant +pixeltype-index4+ sdl3-ffi:+sdl-pixeltype-index4+)
(defconstant +pixeltype-index8+ sdl3-ffi:+sdl-pixeltype-index8+)
(defconstant +pixeltype-packed8+ sdl3-ffi:+sdl-pixeltype-packed8+)
(defconstant +pixeltype-packed16+ sdl3-ffi:+sdl-pixeltype-packed16+)
(defconstant +pixeltype-packed32+ sdl3-ffi:+sdl-pixeltype-packed32+)
(defconstant +pixeltype-arrayu8+ sdl3-ffi:+sdl-pixeltype-arrayu8+)
(defconstant +pixeltype-arrayu16+ sdl3-ffi:+sdl-pixeltype-arrayu16+)
(defconstant +pixeltype-arrayu32+ sdl3-ffi:+sdl-pixeltype-arrayu32+)
(defconstant +pixeltype-arrayf16+ sdl3-ffi:+sdl-pixeltype-arrayf16+)
(defconstant +pixeltype-arrayf32+ sdl3-ffi:+sdl-pixeltype-arrayf32+)

;;; pixel type orderings
(defconstant +bitmaporder-none+ sdl3-ffi:+sdl-bitmaporder-none+)
(defconstant +bitmaporder-4321+ sdl3-ffi:+sdl-bitmaporder-4321+)
(defconstant +bitmaporder-1234+ sdl3-ffi:+sdl-bitmaporder-1234+)
(defconstant +packedorder-none+ sdl3-ffi:+sdl-packedorder-none+)
(defconstant +packedorder-xrgb+ sdl3-ffi:+sdl-packedorder-xrgb+)
(defconstant +packedorder-rgbx+ sdl3-ffi:+sdl-packedorder-rgbx+)
(defconstant +packedorder-argb+ sdl3-ffi:+sdl-packedorder-argb+)
(defconstant +packedorder-rgba+ sdl3-ffi:+sdl-packedorder-rgba+)
(defconstant +packedorder-xbgr+ sdl3-ffi:+sdl-packedorder-xbgr+)
(defconstant +packedorder-bgrx+ sdl3-ffi:+sdl-packedorder-bgrx+)
(defconstant +packedorder-abgr+ sdl3-ffi:+sdl-packedorder-abgr+)
(defconstant +packedorder-bgra+ sdl3-ffi:+sdl-packedorder-bgra+)
(defconstant +arrayorder-none+ sdl3-ffi:+sdl-arrayorder-none+)
(defconstant +arrayorder-rgb+ sdl3-ffi:+sdl-arrayorder-rgb+)
(defconstant +arrayorder-rgba+ sdl3-ffi:+sdl-arrayorder-rgba+)
(defconstant +arrayorder-argb+ sdl3-ffi:+sdl-arrayorder-argb+)
(defconstant +arrayorder-bgr+ sdl3-ffi:+sdl-arrayorder-bgr+)
(defconstant +arrayorder-bgra+ sdl3-ffi:+sdl-arrayorder-bgra+)
(defconstant +arrayorder-abgr+ sdl3-ffi:+sdl-arrayorder-abgr+)

;;; pixel format layouts
(defconstant +packedlayout-none+ sdl3-ffi:+sdl-packedlayout-none+)
(defconstant +packedlayout-332+ sdl3-ffi:+sdl-packedlayout-332+)
(defconstant +packedlayout-4444+ sdl3-ffi:+sdl-packedlayout-4444+)
(defconstant +packedlayout-1555+ sdl3-ffi:+sdl-packedlayout-1555+)
(defconstant +packedlayout-5551+ sdl3-ffi:+sdl-packedlayout-5551+)
(defconstant +packedlayout-565+ sdl3-ffi:+sdl-packedlayout-565+)
(defconstant +packedlayout-8888+ sdl3-ffi:+sdl-packedlayout-8888+)
(defconstant +packedlayout-2101010+ sdl3-ffi:+sdl-packedlayout-2101010+)
(defconstant +packedlayout-1010102+ sdl3-ffi:+sdl-packedlayout-1010102+)

;;; texture access patterns
(defconstant +textureaccess-static+ sdl3-ffi:+sdl-textureaccess-static+)
(defconstant +textureaccess-streaming+ sdl3-ffi:+sdl-textureaccess-streaming+)
(defconstant +textureaccess-target+ sdl3-ffi:+sdl-textureaccess-target+)

;;; renderer properties
(defconstant +prop-renderer-name-string+ sdl3-ffi:+sdl-prop-renderer-name-string+)
(defconstant +prop-renderer-window-pointer+ sdl3-ffi:+sdl-prop-renderer-window-pointer+)
(defconstant +prop-renderer-surface-pointer+ sdl3-ffi:+sdl-prop-renderer-surface-pointer+)
(defconstant +prop-renderer-vsync-number+ sdl3-ffi:+sdl-prop-renderer-vsync-number+)
(defconstant +prop-renderer-max-texture-size-number+ sdl3-ffi:+sdl-prop-renderer-max-texture-size-number+)
(defconstant +prop-renderer-texture-formats-pointer+ sdl3-ffi:+sdl-prop-renderer-texture-formats-pointer+)
(defconstant +prop-renderer-output-colorspace-number+ sdl3-ffi:+sdl-prop-renderer-output-colorspace-number+)
(defconstant +prop-renderer-hdr-enabled-boolean+ sdl3-ffi:+sdl-prop-renderer-hdr-enabled-boolean+)
(defconstant +prop-renderer-sdr-white-point-float+ sdl3-ffi:+sdl-prop-renderer-sdr-white-point-float+)
(defconstant +prop-renderer-hdr-headroom-float+ sdl3-ffi:+sdl-prop-renderer-hdr-headroom-float+)
(defconstant +prop-renderer-d3d9-device-pointer+ sdl3-ffi:+sdl-prop-renderer-d3d9-device-pointer+)
(defconstant +prop-renderer-d3d11-device-pointer+ sdl3-ffi:+sdl-prop-renderer-d3d11-device-pointer+)
(defconstant +prop-renderer-d3d11-swapchain-pointer+ sdl3-ffi:+sdl-prop-renderer-d3d11-swapchain-pointer+)
(defconstant +prop-renderer-d3d12-device-pointer+ sdl3-ffi:+sdl-prop-renderer-d3d12-device-pointer+)
(defconstant +prop-renderer-d3d12-swapchain-pointer+ sdl3-ffi:+sdl-prop-renderer-d3d12-swapchain-pointer+)
(defconstant +prop-renderer-d3d12-command-queue-pointer+ sdl3-ffi:+sdl-prop-renderer-d3d12-command-queue-pointer+)
(defconstant +prop-renderer-vulkan-instance-pointer+ sdl3-ffi:+sdl-prop-renderer-vulkan-instance-pointer+)
(defconstant +prop-renderer-vulkan-surface-number+ sdl3-ffi:+sdl-prop-renderer-vulkan-surface-number+)
(defconstant +prop-renderer-vulkan-physical-device-pointer+ sdl3-ffi:+sdl-prop-renderer-vulkan-physical-device-pointer+)
(defconstant +prop-renderer-vulkan-device-pointer+ sdl3-ffi:+sdl-prop-renderer-vulkan-device-pointer+)
(defconstant +prop-renderer-vulkan-graphics-queue-family-index-number+ sdl3-ffi:+sdl-prop-renderer-vulkan-graphics-queue-family-index-number+)
(defconstant +prop-renderer-vulkan-present-queue-family-index-number+ sdl3-ffi:+sdl-prop-renderer-vulkan-present-queue-family-index-number+)
(defconstant +prop-renderer-vulkan-swapchain-image-count-number+ sdl3-ffi:+sdl-prop-renderer-vulkan-swapchain-image-count-number+)
(defconstant +prop-renderer-gpu-device-pointer+ sdl3-ffi:+sdl-prop-renderer-gpu-device-pointer+)

(defconstant +prop-renderer-create-name-string+ sdl3-ffi:+sdl-prop-renderer-create-name-string+)
(defconstant +prop-renderer-create-window-pointer+ sdl3-ffi:+sdl-prop-renderer-create-window-pointer+)
(defconstant +prop-renderer-create-surface-pointer+ sdl3-ffi:+sdl-prop-renderer-create-surface-pointer+)
(defconstant +prop-renderer-create-output-colorspace-number+ sdl3-ffi:+sdl-prop-renderer-create-output-colorspace-number+)
(defconstant +prop-renderer-create-present-vsync-number+ sdl3-ffi:+sdl-prop-renderer-create-present-vsync-number+)
(defconstant +prop-renderer-create-vulkan-instance-pointer+ sdl3-ffi:+sdl-prop-renderer-create-vulkan-instance-pointer+)
(defconstant +prop-renderer-create-vulkan-surface-number+ sdl3-ffi:+sdl-prop-renderer-create-vulkan-surface-number+)
(defconstant +prop-renderer-create-vulkan-physical-device-pointer+ sdl3-ffi:+sdl-prop-renderer-create-vulkan-physical-device-pointer+)
(defconstant +prop-renderer-create-vulkan-device-pointer+ sdl3-ffi:+sdl-prop-renderer-create-vulkan-device-pointer+)
(defconstant +prop-renderer-create-vulkan-graphics-queue-family-index-number+ sdl3-ffi:+sdl-prop-renderer-create-vulkan-graphics-queue-family-index-number+)
(defconstant +prop-renderer-create-vulkan-present-queue-family-index-number+ sdl3-ffi:+sdl-prop-renderer-create-vulkan-present-queue-family-index-number+)

;;; texture properties
(defconstant +prop-texture-colorspace-number+ sdl3-ffi:+sdl-prop-texture-colorspace-number+)
(defconstant +prop-texture-format-number+ sdl3-ffi:+sdl-prop-texture-format-number+)
(defconstant +prop-texture-access-number+ sdl3-ffi:+sdl-prop-texture-access-number+)
(defconstant +prop-texture-width-number+ sdl3-ffi:+sdl-prop-texture-width-number+)
(defconstant +prop-texture-height-number+ sdl3-ffi:+sdl-prop-texture-height-number+)
(defconstant +prop-texture-sdr-white-point-float+ sdl3-ffi:+sdl-prop-texture-sdr-white-point-float+)
(defconstant +prop-texture-hdr-headroom-float+ sdl3-ffi:+sdl-prop-texture-hdr-headroom-float+)
(defconstant +prop-texture-d3d11-texture-pointer+ sdl3-ffi:+sdl-prop-texture-d3d11-texture-pointer+)
(defconstant +prop-texture-d3d11-texture-u-pointer+ sdl3-ffi:+sdl-prop-texture-d3d11-texture-u-pointer+)
(defconstant +prop-texture-d3d11-texture-v-pointer+ sdl3-ffi:+sdl-prop-texture-d3d11-texture-v-pointer+)
(defconstant +prop-texture-d3d12-texture-pointer+ sdl3-ffi:+sdl-prop-texture-d3d12-texture-pointer+)
(defconstant +prop-texture-d3d12-texture-u-pointer+ sdl3-ffi:+sdl-prop-texture-d3d12-texture-u-pointer+)
(defconstant +prop-texture-d3d12-texture-v-pointer+ sdl3-ffi:+sdl-prop-texture-d3d12-texture-v-pointer+)
(defconstant +prop-texture-opengl-texture-number+ sdl3-ffi:+sdl-prop-texture-opengl-texture-number+)
(defconstant +prop-texture-opengl-texture-uv-number+ sdl3-ffi:+sdl-prop-texture-opengl-texture-uv-number+)
(defconstant +prop-texture-opengl-texture-u-number+ sdl3-ffi:+sdl-prop-texture-opengl-texture-u-number+)
(defconstant +prop-texture-opengl-texture-v-number+ sdl3-ffi:+sdl-prop-texture-opengl-texture-v-number+)
(defconstant +prop-texture-opengl-texture-target-number+ sdl3-ffi:+sdl-prop-texture-opengl-texture-target-number+)
(defconstant +prop-texture-opengl-tex-w-float+ sdl3-ffi:+sdl-prop-texture-opengl-tex-w-float+)
(defconstant +prop-texture-opengl-tex-h-float+ sdl3-ffi:+sdl-prop-texture-opengl-tex-h-float+)
(defconstant +prop-texture-opengles2-texture-number+ sdl3-ffi:+sdl-prop-texture-opengles2-texture-number+)
(defconstant +prop-texture-opengles2-texture-uv-number+ sdl3-ffi:+sdl-prop-texture-opengles2-texture-uv-number+)
(defconstant +prop-texture-opengles2-texture-u-number+ sdl3-ffi:+sdl-prop-texture-opengles2-texture-u-number+)
(defconstant +prop-texture-opengles2-texture-v-number+ sdl3-ffi:+sdl-prop-texture-opengles2-texture-v-number+)
(defconstant +prop-texture-opengles2-texture-target-number+ sdl3-ffi:+sdl-prop-texture-opengles2-texture-target-number+)
(defconstant +prop-texture-vulkan-texture-number+ sdl3-ffi:+sdl-prop-texture-vulkan-texture-number+)
;;; texture create properties
(defconstant  +prop-texture-create-colorspace-number+ sdl3-ffi:+sdl-prop-texture-create-colorspace-number+)
(defconstant  +prop-texture-create-format-number+ sdl3-ffi:+sdl-prop-texture-create-format-number+)
(defconstant  +prop-texture-create-access-number+ sdl3-ffi:+sdl-prop-texture-create-access-number+)
(defconstant  +prop-texture-create-width-number+ sdl3-ffi:+sdl-prop-texture-create-width-number+)
(defconstant  +prop-texture-create-height-number+ sdl3-ffi:+sdl-prop-texture-create-height-number+)
(defconstant  +prop-texture-create-sdr-white-point-float+ sdl3-ffi:+sdl-prop-texture-create-sdr-white-point-float+)
(defconstant  +prop-texture-create-hdr-headroom-float+ sdl3-ffi:+sdl-prop-texture-create-hdr-headroom-float+)
(defconstant  +prop-texture-create-d3d11-texture-pointer+ sdl3-ffi:+sdl-prop-texture-create-d3d11-texture-pointer+)
(defconstant  +prop-texture-create-d3d11-texture-u-pointer+ sdl3-ffi:+sdl-prop-texture-create-d3d11-texture-u-pointer+)
(defconstant  +prop-texture-create-d3d11-texture-v-pointer+ sdl3-ffi:+sdl-prop-texture-create-d3d11-texture-v-pointer+)
(defconstant  +prop-texture-create-d3d12-texture-pointer+ sdl3-ffi:+sdl-prop-texture-create-d3d12-texture-pointer+)
(defconstant  +prop-texture-create-d3d12-texture-u-pointer+ sdl3-ffi:+sdl-prop-texture-create-d3d12-texture-u-pointer+)
(defconstant  +prop-texture-create-d3d12-texture-v-pointer+ sdl3-ffi:+sdl-prop-texture-create-d3d12-texture-v-pointer+)
(defconstant  +prop-texture-create-metal-pixelbuffer-pointer+ sdl3-ffi:+sdl-prop-texture-create-metal-pixelbuffer-pointer+)
(defconstant  +prop-texture-create-opengl-texture-number+ sdl3-ffi:+sdl-prop-texture-create-opengl-texture-number+)
(defconstant  +prop-texture-create-opengl-texture-uv-number+ sdl3-ffi:+sdl-prop-texture-create-opengl-texture-uv-number+)
(defconstant  +prop-texture-create-opengl-texture-u-number+ sdl3-ffi:+sdl-prop-texture-create-opengl-texture-u-number+)
(defconstant  +prop-texture-create-opengl-texture-v-number+ sdl3-ffi:+sdl-prop-texture-create-opengl-texture-v-number+)
(defconstant  +prop-texture-create-opengles2-texture-number+ sdl3-ffi:+sdl-prop-texture-create-opengles2-texture-number+)
(defconstant  +prop-texture-create-opengles2-texture-uv-number+ sdl3-ffi:+sdl-prop-texture-create-opengles2-texture-uv-number+)
(defconstant  +prop-texture-create-opengles2-texture-u-number+ sdl3-ffi:+sdl-prop-texture-create-opengles2-texture-u-number+)
(defconstant  +prop-texture-create-opengles2-texture-v-number+ sdl3-ffi:+sdl-prop-texture-create-opengles2-texture-v-number+)
(defconstant  +prop-texture-create-vulkan-texture-number+ sdl3-ffi:+sdl-prop-texture-create-vulkan-texture-number+)
